services:
  mongo:
    image: mongo:7
    container_name: mern-mongo-container
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
    image: mern-backend
    container_name: mern-backend-container
    restart: unless-stopped
    environment:
      PORT: 5000
      MONGO_URI: mongodb://mongo:27017/simple-mern-todo
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: /api
    image: mern-frontend
    container_name: mern-frontend-container
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo-data:
